name: Daily Featured Post

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC daily
  workflow_dispatch:

jobs:
  update-featured-post:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Update Featured Post
        run: ./scripts/run-update-featured.sh
